name: doc
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install doxygen python3-breathe python3-sphinx-rtd-theme
    - name: Render
      run: make -C docs
